-- Seed file for Book Club books
-- Place in supabase/seeds/books.sql

insert into public.bookclub_books (title, author, description, cover_image_path, buy_url, reading_date) values
('When Money Dies', 'Adam Fergusson', 'A historical account of hyperinflation in Weimar Germany and its devastating economic and social consequences.', NULL, 'https://a.co/d/b9ItA14', '2025-04-16'),
('The Genesis Book', 'Aaron van Wirdum', 'A concise history of the people, projects, and ideas—spanning cryptography, cypherpunk movements, and heterodox economics—that laid the foundation for Bitcoins creation', NULL, 'https://thegenesisbook.com', '2024-08-21'),
('Salt: A World History', 'Mark Kurlansky', 'A fascinating history of salt''s role in shaping civilizations, trade, and global economies.', NULL, 'https://www.barnesandnoble.com/w/salt-mark-kurlansky/1102487050', NULL),
('24', 'Avi Burra', 'A gripping narrative exploring themes of technology, freedom, and societal transformation.', NULL, 'https://a.co/d/5Qk9f18', NULL),
('Mandibles', 'Lionel Shriver', 'A dystopian novel depicting a family''s struggle in a future America facing economic collapse.', NULL, 'https://a.co/d/6N0BUBQ', NULL),
('Check Your Financial Privilege', 'Alex Gladstein', 'An analysis of global financial systems and Bitcoin''s potential to empower the underprivileged.', NULL, 'https://a.co/d/c5qe28j', NULL),
('Lords of Finance', 'Liaquat Ahamed', 'A Pulitzer Prize-winning history of central bankers and their role in the Great Depression.', NULL, 'https://a.co/d/10exmxD', NULL),
('The Creature from Jekyll Island', 'G. Edward Griffin', 'An exposé on the Federal Reserve''s creation and its impact on modern finance.', NULL, 'https://a.co/d/fBffbNj', '2025-01-22'),
('Softwar', 'Jason Lowery', 'A thesis on Bitcoin as a strategic tool for national security and digital warfare.', NULL, 'https://a.co/d/0dOzGhV', NULL),
('Would Mao Hold Bitcoin?', 'Roger Huang', 'A thought-provoking analysis of Bitcoin''s ideological implications in authoritarian regimes.', NULL, 'https://store.bitcoinmagazine.com/products/would-mao-hold-bitcoin', NULL),
('A History of Central Banking and the Enslavement of Mankind', 'Stephen Goodson', 'A critical examination of central banking''s historical role in economic control.', NULL, 'https://archive.org/details/stephen-goodson-a-history-of-central-banking-and-the-enslavement-of-mankind.org/mode/2up', NULL),
('Hidden Repression', 'Alex Gladstein', 'An exploration of financial censorship and Bitcoin''s role in promoting freedom.', NULL, 'https://a.co/d/at5LKyX', '2025-03-19'),
('Bitcoin is Venice', 'Allen Farrington and Sacha Meyers', 'A philosophical comparison of Bitcoin to Venice''s historical economic resilience.', NULL, 'https://store.bitcoinmagazine.com/products/bitcoin-is-venice', NULL),
('Abundance Through Scarcity', 'Loni Appelberg', 'An exploration of how scarcity drives innovation and value in economics and technology.', NULL, 'https://amzn.to/3BDs4EM', '2025-02-26'),
('The 7th Property', 'Erik Yakes', 'A deep dive into Bitcoin as a unique asset class in modern finance.', NULL, 'https://yakes.io/book', NULL),
('The Sovereign Individual', 'James Dale Davidson & Lord William Rees-Mogg', 'A visionary prediction of how digital technology empowers individual sovereignty.', NULL, 'https://a.co/d/hhqdL5Q', '2024-10-23'),
('The Blocksize War', 'Jonathan Bier', 'A detailed chronicle of Bitcoin''s scaling debates and community conflicts.', NULL, 'https://a.co/d/9mCLrOf', '2024-07-09'),
('Resistance Money', 'Andrew M. Bailey, Bradley Rettler, Craig Warmke', 'A philosophical and economic case for Bitcoin as a tool for financial resistance.', NULL, 'https://www.resistance.money', NULL),
('The Ethics of Money Production', 'Jörg Guido Hülsmann', 'A moral critique of modern money creation and its societal impacts.', NULL, 'https://mises.org/library/book/ethics-money-production', '2024-11-20'),
('Paper Soldiers', 'Saleha Mohsin', 'An investigation into the U.S. dollar''s global dominance and its vulnerabilities.', NULL, 'https://tinyurl.com/SalehaDollar', '2024-09-24'),
('The Bushido of Bitcoin', 'Aleksandar Svetski', 'A philosophical guide to Bitcoin''s principles, inspired by samurai ethics.', NULL, 'https://www.bushidoofbitcoin.com', NULL),
('Chasing the Seeds (The Fiefdom Chronicles Book 1)', 'Devin Rose', 'A fictional tale weaving themes of decentralization and societal change.', NULL, 'https://a.co/d/dL6qsq4', NULL),
('Bitcoin: Hard Money You Can''t F*ck With', 'Jason A. Williams', 'A bold defense of Bitcoin as incorruptible, hard money for the future.', NULL, 'https://bitcoinhard.money', NULL),
('Price of Time', 'Edward Chancellor', 'An analysis of interest rates and their long-term effects on economic cycles.', NULL, 'https://a.co/d/fE8WYMV', NULL),
('Why Bitcoin?', 'Tomer Strolight', 'A concise explanation of Bitcoin''s value proposition and transformative potential.', NULL, 'https://whybitcoinbook.com/', NULL),
('Superagency: What Could Possibly Go Right with Our AI Future?', 'Reid Hoffman & Greg Beato', 'An optimistic exploration of AI''s potential to enhance human agency.', NULL, 'https://a.co/d/hnxqV0u', NULL),
('Free Private Cities: Making Governments Compete For You', 'Titus Gebel', 'A proposal for private cities as a model for competitive governance.', NULL, 'https://a.co/d/90PgAG1', NULL),
('Bitcoin Age', 'Nik Bhatia', 'A vision of how Bitcoin reshapes global finance in the digital era.', NULL, 'https://thebitcoinlayer.com/bitcoinage', NULL),
('The Satoshi Papers', 'Natalie Smolenski', 'A collection of essays exploring Bitcoin''s cultural and economic significance.', NULL, 'https://store.bitcoinmagazine.com/pages/the-satoshi-papers', NULL),
('The Big Print', 'Lawrence Lepard', 'A critique of inflationary monetary policies and their societal consequences.', NULL, 'https://a.co/d/3RLY4UX', NULL),
('Price of Tomorrow', 'Jeff Booth', 'An argument for embracing deflationary technology to solve economic challenges.', NULL, 'https://a.co/d/4qW589F', NULL),
('The Deficit Myth', 'Stephanie Kelton', 'A modern monetary theory perspective on government deficits and fiscal policy.', NULL, 'https://a.co/d/89rsms4', NULL);